#!/bin/bash

# Manual Test Steps - AdaReach SMS Dashboard
# Developed by: Md. Ainul Moin Noor

echo "🧪 AdaReach SMS Dashboard - Manual Test Steps"
echo "=============================================="
echo ""
echo "Follow these steps in separate terminals:"
echo ""

echo "📋 TERMINAL 1 - Start Redis"
echo "----------------------------"
echo "redis-server"
echo ""

echo "📋 TERMINAL 2 - Start Socket.IO Server"
echo "---------------------------------------"
echo "cd /home/noor/codes/robisms/robi-sms-package/adarearch-laravel"
echo "nvm use 19.8.1"
echo "./start-socket-server.sh"
echo ""

echo "📋 TERMINAL 3 - Test App Setup (First Time Only)"
echo "------------------------------------------------"
echo "cd /home/noor/codes/robisms"
echo "composer create-project laravel/laravel sms-test-app"
echo "cd sms-test-app"
echo ""
echo "# Add to composer.json:"
echo "composer config repositories.local '{\"type\": \"path\", \"url\": \"../robi-sms-package/adarearch-laravel\"}'"
echo "composer require chandan07cse/robi-sms:@dev"
echo ""
echo "# Publish assets:"
echo "php artisan vendor:publish --tag=adarearch-config"
echo "php artisan vendor:publish --tag=adarearch-assets"
echo ""
echo "# Configure .env (add these lines):"
echo "ADAREARCH_USERNAME=your_api_username"
echo "ADAREARCH_PASSWORD=your_api_password"
echo "ADAREARCH_DEFAULT_SENDER=TEST"
echo "REDIS_HOST=127.0.0.1"
echo "REDIS_PORT=6379"
echo "BROADCAST_DRIVER=redis"
echo "SOCKET_IO_SERVER_PORT=3000"
echo ""

echo "📋 TERMINAL 3 - Start Dashboard"
echo "--------------------------------"
echo "cd /home/noor/codes/robisms/sms-test-app"
echo "php artisan adarearch:serve --port=8090"
echo ""

echo "🌐 BROWSER - Open Dashboard"
echo "----------------------------"
echo "http://localhost:8090/sms-dashboard"
echo ""

echo "🎯 Quick Test Features:"
echo "----------------------"
echo "1. Dashboard → View overview with charts"
echo "2. Send SMS → Fill form and send test SMS"
echo "3. SMS Messages → View sent messages with filters"
echo "4. Analytics → Check charts and statistics"
echo "5. Settings → See developer credit (Md. Ainul Moin Noor)"
echo ""

echo "✅ Success Indicators:"
echo "---------------------"
echo "- 🟢 Green dot in dashboard header = Real-time connected"
echo "- 📱 Toast notifications appear when SMS sent"
echo "- 📊 Charts update with data"
echo "- 💳 Credit balance displays"
echo ""

echo "📝 Test SMS Sending:"
echo "-------------------"
echo "# In Laravel tinker or controller:"
echo "php artisan tinker"
echo ""
echo "use AdaReach\\Sms\\Facades\\AdaReach;"
echo ""
echo "AdaReach::to('01712345678')"
echo "    ->from('TEST')"
echo "    ->message('Test from AdaReach Dashboard')"
echo "    ->send();"
echo ""

echo "🔍 Check Logs:"
echo "-------------"
echo "# Socket.IO logs:"
echo "tail -f /tmp/socket-io.log"
echo ""
echo "# Laravel logs:"
echo "tail -f storage/logs/laravel.log"
echo ""

echo "🛑 Stop Services:"
echo "----------------"
echo "# Press Ctrl+C in each terminal"
echo "# Or kill processes:"
echo "pkill redis-server"
echo "pkill -f socket-server.js"
echo "pkill -f 'artisan adarearch:serve'"
echo ""

echo "================================================"
echo "Ready to test! Start with Terminal 1 (Redis)"
echo "================================================"
